### ISSUE TITLE
Ansible version recommandation

### ISSUE THREAD

**Issue by srnfr** [networkop/kolla-odl-bgpvpn#2]
Had problems running the playbook with Ansible 2.4 (the CallBackModule was claiming that no parameter was set).
Downgrading to Ansible 2.2 is a successful workaround.

@networkop : Maybe you should give some hints on the Ansible version

**Comment by networkop** [comment]
thanks, haven't tried it with 2.4 yet. this is most likely due to the custom callback plugin. try removing callback_plugins from ansible.cfg that should fix the issue. and i'll see if i can get the plugin to work with 2.4.

**Comment by networkop** [comment]
also fixed. ansble and jinja should now be installed from requirements.txt.
